[package]
name = "aspotify"
description = "Asynchronous client for the Spotify API"
version = "0.1.0"
readme = "README.md"
repository = "https://github.com/KaiJewson/aspotify"
keywords = ["Spotify", "API", "Asynchronous"]
categories = ["api-bindings", "asynchronous", "authentication", "web-programming", "web-programming::http-client"]
license = "MIT OR Apache-2.0"
authors = ["KaiJewson <58880148+KaiJewson@users.noreply.github.com>"]
edition = "2018"

[dependencies]
reqwest = "0.10.0"
tokio = { version = "0.2.6", features = ["time"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_millis = "0.1.1"
chrono = { version = "0.4.10", features = ["serde"] }
lazy_static = "1.4.0"
isocountry = "0.2.0"
isolanguage-1 = { version = "0.1.0", features = ["serde_support"] }
rand = "0.7.2"
serde_json = "1.0.44"
base64 = "0.11.0"

[dev-dependencies]
dotenv = "0.15.0"
tokio = { version = "0.2.6", features = ["time", "macros"] }
