[package]
name = "aspotify"
description = "Asynchronous client for the Spotify API"
version = "0.0.1"
readme = "README.md"
keywords = ["Spotify", "API", "Asynchronous"]
categories = ["api-bindings", "asynchronous", "authentication", "web-programming", "web-programming::http-client"]
license = "MIT OR Apache-2.0"
authors = ["KaiJewson <58880148+KaiJewson@users.noreply.github.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.0-alpha.2", features = ["json"] }
tokio = "0.2.0-alpha.6"
serde = { version = "1.0.104", features = ["derive"] }
serde_millis = "0.1.1"
chrono = { version = "0.4.10", features = ["serde"] }
lazy_static = "1.4.0"
isocountry = "0.2.0"
isolanguage-1 = { version = "0.1.0", features = ["serde_support"] }

# TEMPORARY, ONLY FOR DEBUGGING REMOVE AFTER U REMOVE THE #[cfg(test)] non-test PRINTS
serde_json = "1.0.42"

[dev-dependencies]
dotenv = "0.15.0"
